### PR TITLE
Initial work for APE 2.0.0 by adding populator code

### PR DESCRIPTION
**Pull request by lordofthejars**
Initial work for APE 2.0.0 by adding populator code

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
There were several issues with this PR - primarily mvn build was failing. This was fixed in @035014f.

**Comment by bartoszmajsak** [comment]
I would like to suggest that all ftest projects could be suffixed with `-ftest` instead of prefixed. This way it would be easier to navigate between module (e.g. mongo) and corresponding functional tests. That could also be applied to Cube. WDYT?

**Comment by lordofthejars** [comment]
@bartoszmajsak I think that the PR is good, let me suffix `ftest` tests and then we can merge.

**Comment by lordofthejars** [comment]
@bartoszmajsak Ready to be merged.

**Comment by bartoszmajsak** [comment]
@lordofthejars not sure, let's discuss it f2f.

**Comment by lordofthejars** [comment]
Let's discuss, but at the end is the 2.X branch so it should be no problem at all.

**Comment by bartoszmajsak** [comment]
Branch does not matter here, it's more about things to clean up before, as we have a great opportunity now.

**Comment by bartoszmajsak** [comment]
Two things to polish before we merge:
- [ ] I'm not sure all of `-api` modules are really APIs and contain what user should have access to - let's  review @bartoszmajsak
- [ ] Let's not leak classes outside boundaries they are used - not everything needs to be public @lordofthejars

**Pull request merged**
